display_name: ntpizza
url: https://github.com/ntpizza/ntpizza-next/
license: Other

packager: ntpizza
packagerEmail: linux@ntpizza.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/source/ic_launcher_border.png

keywords:
  - ntpizza
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: ntpizza

group: Applications/Internet

startup_notify: true
