display_name: ntpizza
package_name: ntpizza
maintainer:
  name: ntpizza
  email: linux@ntpizza.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/source/ic_launcher_border.png

postinstall_scripts:
  - echo "Installed ntpizza"
postuninstall_scripts:
  - echo "Surprised Why?"

keywords:
  - ntpizza
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: ntpizza

categories:
  - Network

startup_notify: true
